# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=5, unique=True)),
                ('customer_id', models.IntegerField()),
                ('delivery_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.TextField(blank=True)),
                ('delivery_street', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('delivery_city', models.CharField(max_length=255)),
                ('delivery_country', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_product', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cod', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=5)),
                ('paid', models.CharField(max_length=3)),
                ('delivery_note', models.TextField()),
                ('date_of_addition_order', models.DateField(auto_now=True)),
                ('order_status', models.CharField(choices=[(1, 'New'), (2, 'In preparation'), (3, 'Wait for products'), (4, 'Wrong customer data'), (5, 'Canceled due by address'), (6, 'DELIVERED'), (7, 'RETURN')], default=1, max_length=4)),
                ('order_status_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
