# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
