# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_exchange', '0002_auto_20180602_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_of_addition_order',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status_date',
            field=models.DateField(auto_now=True),
        ),
    ]
